In [1]:
import numpy as np
import pandas as pd

import matplotlib.pylab as plt


df = pd.read_csv(u'../data/iris.txt',sep=' ')
df

sl   sw   pl   pw  c
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  3
121  5.6  2.8  4.9  2.0  3
122  7.7  2.8  6.7  2.0  3
123  6.3  2.7  4.9  1.8  3
124  6.7  3.3  5.7  2.1  3
125  7.2  3.2  6.0  1.8  3
126  6.2  2.8  4.8  1.8  3
127  6.1  3.0  4.9  1.8  3
128  6.4  2.8  5.6  2.1  3
129  7.2  3.0  5.8  1.6  3
130  7.4  2.8  6.1  1.9  3
131  7.9  3.8  6.4  2.0  3
132  6.4  2.8  5.6  2.2  3
133  6.3  2.8  5.1  1.5  3
134  6.1  2.6  5.6  1.4  3
135  7.7  3.0  6.1  2.3  3
136  6.3  3.4  5.6  2.4  3
137  6.4  3.1  5.5  1.8  3
138  6.0  3.0  4.8  1.8  3
139  6.9  3.1  5.4  2.1  3
140  6.7  3.1  5.6  2.4  3
141  6.9  3.1  5.1  2.3  3
142  5.8  2.7  5.1  1.9  3
143  6.8  3.2  5.9  2.3  3
144  6.7  3.3  5.7  2.5  3
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [2]:
A = np.hstack([
        np.matrix(df.sl).T, 
        np.matrix(df.sw).T, 
        np.matrix(df.pl).T, 
        np.matrix(df.pw).T])
A[:5] # sample view

matrix([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2]])

In [3]:
c = np.matrix(df.c).T
c

matrix([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],

In [4]:
def distance(A,x):
    '''A is a NxD matrix where N is the number of samples and D is
       the dimension of the feature set
    '''
    N = A.shape[0]
    d = np.zeros((N,1))
    
    md = np.inf
    
    for i in range(N):
        e = A[i,:]- x
        d[i] = np.sum(e*e.T)
        if d[i]<md:
            md = d[i]
            min_idx = i
    
    return d, min_idx
    
    

#x_test = np.mat('[3.3, 2.5,5.5,1.7]')

x_test = A[1,:] + 5*np.random.randn(1,4)

d, idx = distance(A, x_test)
float(c[idx])

1.0

In [5]:
def leave_one_out(A, c, W):
    
    N = A.shape[0]   

    correct = 0
    
    
    for j in range(N):
        md = np.inf
        for i in range(N):
            if i != j:
                e = A[i,:]- A[j,:]
                e = e.reshape((4,1))
                d = e.T*W*e
                if d<md:
                    md = d
                    min_idx = i
        if c[min_idx] == c[j]:
            correct += 1
    
    accuracy = 1.*correct/N
    return accuracy
    
    
    

In [7]:
W = np.matrix(np.diag([2,1,0,2]))
print(W)

acc = leave_one_out(A, c, W)
print(acc)

[[2 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 2]]
0.9533333333333334


In [134]:
## Use a heap to store the smallest items

import heapq as hp

# Define an object and overload custom comparison operators
class tup:
    def __init__(self, val, idx):
        self.val = val
        self.idx = idx
        
    def __lt__(self, other):
        '''Redefine for max-heap'''
        return self.val > other.val
    
    def __le__(self, other):
        return self.val <= other.val
 
    def __eq__(self, other):
        return self.val == other.val
    
    def __ne__(self, other):
        return self.val != other.val

    def __gt__(self, other):
        return self.val > other.val

    def __ge__(self, other):
        return self.val >= other.val

    def __str__(self):
        return '{:.3},{:d}'.format(self.val,self.idx)
    
        
## Search for the nearest K   
K = 20
heap = []
N = A.shape[0]   

for j in range(N):
    heap = []
    ## Fill in the heap with dummy nodes
    for k in range(K):
        hp.heappush(heap, tup(np.inf, -1))

    for i in range(N):
        if i != j:
            e = A[i,:]- A[j,:]
            e = e.reshape((4,1))
            tp = tup(float(e.T*e), i)
            if tp <= heap[0]:
                hp.heapreplace(heap, tp)

    for t in range(len(heap)):
        h = hp.heappop(heap)
        print(h, float(c[h.idx]))
    print('--'*5)


0.21,43 1.0
0.19,20 1.0
0.17,36 1.0
0.15,31 1.0
0.14,10 1.0
0.14,11 1.0
0.14,35 1.0
0.13,46 1.0
0.11,19 1.0
0.1,26 1.0
0.09,48 1.0
0.09,21 1.0
0.05,49 1.0
0.03,7 1.0
0.03,40 1.0
0.02,28 1.0
0.02,27 1.0
0.02,39 1.0
0.02,4 1.0
0.01,17 1.0
----------
0.26,8 1.0
0.26,38 1.0
0.25,26 1.0
0.25,28 1.0
0.21,11 1.0
0.21,39 1.0
0.18,7 1.0
0.13,47 1.0
0.12,29 1.0
0.11,3 1.0
0.1,49 1.0
0.09,2 1.0
0.09,35 1.0
0.06,30 1.0
0.05,25 1.0
0.03,9 1.0
0.03,37 1.0
0.03,34 1.0
0.02,12 1.0
0.02,45 1.0
----------
0.22,25 1.0
0.19,8 1.0
0.19,40 1.0
0.17,7 1.0
0.14,11 1.0
0.13,38 1.0
0.11,30 1.0
0.11,49 1.0
0.1,34 1.0
0.1,9 1.0
0.1,37 1.0
0.1,35 1.0
0.09,1 1.0
0.09,29 1.0
0.09,42 1.0
0.07,12 1.0
0.07,45 1.0
0.07,6 1.0
0.06,3 1.0
0.02,47 1.0
----------
0.27,13 1.0
0.26,35 1.0
0.25,7 1.0
0.21,49 1.0
0.18,25 1.0
0.14,11 1.0
0.11,1 1.0
0.11,6 1.0
0.1,37 1.0
0.1,9 1.0
0.1,34 1.0
0.09,8 1.0
0.09,38 1.0
0.09,42 1.0
0.07,12 1.0
0.07,45 1.0
0.06,2 1.0
0.05,30 1.0
0.03,29 1.0
0.02,47 1.0
----------
0.26,2 1.0
0.25,31 1.0
0